title = "Shan Islam"
baseURL = "https://shan-data-science.co.uk"
languageCode = "en-uk"
theme = "gohugo-theme-ananke"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-96884074-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Data Scientist continuing to learn and share"
  facebook = ""
  twitter = "https://twitter.com/_ShanIslam"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/shahnurislam"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/ai-blur-codes-577585.jpg"
  recent_posts_number = 3
