baseurl = "https://shan-data-science.co.uk"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Shan Data Scientist to be!"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "https-shahnurislam-github-io"
googleAnalytics = "UA-96884074-1"
paginate = 5

[Params]
  logo = "img/Logo.png"
  favicon = "img/favicon (1).ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  useHLJS = true
  
  [Author]
  name = "Shan Islam"
  website = "http://shan-data-science.co.uk/"
  github = "ShahnurIslam"
  twitter = "5hanIslam"
  linkedin = "shahnurislam"
  
  
  [[menu.main]]
    name = "About Me"
    url = "page/about/"
    weight = 1
    
    [[menu.main]]
    identifier = "Resources"
    name = "Resources"
    weight = 2
    
    [[menu.main]]
    identifier = "Code"
    name = "code"
    weight = 1
    
    [[menu.main]]
    parent = "Code"
    name = "Python"
    url = "page/python"
    weight = 2
    
    [[menu.main]]
    parent = "Code"
    name = "R"
    url = "page/R"
    weight = 2

    [[menu.main]]
    parent = "Resources"
    name = "John Mackintosh"
    url = "https://www.johnmackintosh.com/"
    weight = 1